[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "About"
pageRef = "/about/"
weight = 20

[[main]]
name = "Posts"
pageRef = "/posts/"
weight = 30

[[main]]
name = "Projects"
pageRef = "/projects/"
weight = 40

[[main]]
name = "Milo"
pageRef = "/projects/milo/"
parent = "Projects"
weight = 1

[[main]]
name = "Tags"
pageRef = "/tags/"
weight = 50

[[social]]
name = "LinkedIn"
pre = "fab linkedin"
url = "https://linkedin.com/in/dominicbraam/"
weight = 10

[[social]]
name = "GitHub"
pre = "fab fa-github"
url = "https://github.com/dominicbraam"
weight = 20

[[social]]
name = "Email"
pre = "fas envelope"
url = "mailto:dominic.braam@gmail.com"
weight = 30

# toml-docs-start sample-navigation

[[sample]]
name = "Blog"
pageRef = "/blog/"
weight = 10

[[sample]]
name = "Projects"
pageRef = "/projects/"
weight = 20

[[sample]]
name = "Sample project"
pageRef = "/projects/sample-project/"
parent = "Projects"
weight = 1

[[sample]]
name = "Another project"
pageRef = "/projects/another-project/"
parent = "Projects"
weight = 2
# toml-docs-end sample-navigation
